version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: plataforma-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plataforma_servicos
      MYSQL_USER: samuel
      MYSQL_PASSWORD: Cansado
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: