-- Adiciona colunas de auditoria em todas as tabelas
-- criado_por e atualizado_por sao novos em todas as tabelas
-- criado_em e atualizado_em ja existem mas precisam ser padronizados

-- users
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- categories
ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- services
ALTER TABLE services
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- service_images
ALTER TABLE service_images
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- service_orders
ALTER TABLE service_orders
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- reviews
ALTER TABLE reviews
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- favorites
ALTER TABLE favorites
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- reports
ALTER TABLE reports
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- messages
ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

-- enderecos
ALTER TABLE enderecos
    ADD COLUMN IF NOT EXISTS criado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN IF NOT EXISTS atualizado_por VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';